name: "Arlo Local API Server"
version: "1.0.0"
slug: arlo-local
description: >-
  "Local Arlo base station server"
arch:
  - amd64
  - i386
ports:
  123/tcp: 123
  4000/tcp: 4000
  4100/tcp: 4100
  5000/tcp: 5000
map:
  - config:rw