name: "AirPlay Server"
version: "4.3.1"
slug: airplay_shairport_sync
description: >- 
  "Shairport Sync for Hass.io"
startup: application
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
boot: auto
#hassio_api: true,
#homeassistant_api": true,
host_network: true
audio: true
map:
    - config:rw
options:
    log_level: info
    avahi_interfaces:
    avahi_hostname:
    avahi_domainname: local
    airplay_name: Hass.io
    enable_ipv6: false
schema:
    log_level: match(^(trace|debug|info|notice|warning|error|fatal)$)
    avahi_interfaces: str
    avahi_hostname: str
    avahi_domainname: str
    airplay_name: str
    enable_ipv6: bool
image: mikebrady/shairport-sync