name: "AirPlay Server"
version: "4.3.1"
slug: airplay_shairport_sync
description: >- 
  "Shairport Sync for Hass.io"
startup: application
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
boot: auto
#hassio_api: true,
#homeassistant_api": true,
host_network: true
audio: true
init: false
map:
    - config:rw
options:
    airplay_name: Hass.io
schema:
    airplay_name: str
image: mikebrady/shairport-sync