name: "AirPlay Server"
version: "1.0.0"
slug: airplay_shairport_sync
description: >- 
  "Shairport Sync for Hass.io"
startup: application
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
boot: auto
host_network: true
audio: true
init: false
legacy: true
map:
    - config:rw
